MODEL:
  META_ARCHITECTURE: "SemanticFPN"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 101
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  SEM_SEG_HEAD:
    NUM_CLASSES: 2
    LOSS_WEIGHT: 1.0 # why 1 not 0.5?
    USE_LOVASZ: True
    IGNORE_VALUE: 255
DATASETS:
  TRAIN: ("LIP_train",)
  TEST: ("LIP_test",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (54000, 64000)
  MAX_ITER: 75000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2